---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: weather-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: weather-api
  template:
    metadata:
      labels:
        name: weather-api
    spec:
      containers:
      - name: application
        image: frisbex/weather_api
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
# TODO: 
# Add secret for better api key management
